name: Dependabot Auto Merge Pipeline

on:
  pull_request:
    branches:
      - main
      - '*.x'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  auto-merge-dependency-updates:
    name: Automatically Merge Dependabot PRs
    permissions: write-all
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@v7
    with:
      mergeArguments: --auto --rebase
      autoMerge: true

