name: Reusable Build Worflow Caller

on:
  push:
    branches:
      - main
      - master
      - 'feature/*'
  pull_request:
    branches:
      - main
      - master
      - 'feature/*'

 workflow_dispatch:

jobs:
  call-reusable:
    name: Invoke Reusable Build Pipeline
    uses: ./.github/workflows/reusable-build.yml
    with:
      sonar-scan: true
